### ISSUE TITLE
Preview grafana dashboard

### ISSUE THREAD

**Issue by gamingdy** [DrTableBasse/HomeLabV1#1]
Ce serait cool si on pouvait avoir une preview des dashboard grafana, comme ça au lieu de les tester un par un, ou peut directement voir à quoi ça ressemble

**Comment by DrTableBasse** [comment]
Yes totalement d'accord ! je vais ajouter tout ça petit à petit.

Je clôture l'issue quand j'aurais déjà ajouté les dashboards que j'ai 😄

**Comment by DrTableBasse** [comment]
Du coup, je me permets de clôturer cette issue !
Hésite pas à revenir vers moi (en dm ou sur une issue) si tu vois des choses à modifier !!! :smile:
